name: Deploy Pygame Web
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v4 au lieu de v3 pour Node 20+

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install and run Pygbag
        run: |
          python3 -m pip install pygbag
          # On ajoute --no-opt si jamais l'optimisation audio pose problème
          python3 -m pygbag --build .

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
